# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{assert-random}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stewart Matheson"]
  s.date = %q{2010-08-03}
  s.description = %q{This gem adds an assert random assertion that will allow the testing of random sequences. This is handy for game development and anyone working with random numbers with out a way of testing them.}
  s.email = %q{stew@rtmatheson.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "assert-random.gemspec",
     "lib/assert-random.rb",
     "test/helper.rb",
     "test/test_assert-random.rb"
  ]
  s.homepage = %q{http://github.com/stewartmatheson/assert-random}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Adds an assert random assertion to test/unit}
  s.test_files = [
    "test/helper.rb",
     "test/test_assert-random.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

